version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app
    restart: unless-stopped
    # Resource Limits
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    # Healthcheck (zusätzlich zum Dockerfile)
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:3000/']
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    # Verbesserte Sicherheit
    security_opt:
      - no-new-privileges:true
    # Read-only root filesystem
    read_only: true
    # Temporäre Schreibrechte für notwendige Verzeichnisse
    tmpfs:
      - /tmp
      - /app/.next/cache
    # Netzwerk-Isolation
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'

  loki:
    image: grafana/loki:latest
    ports:
      - '3100:3100'
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - '16686:16686'
      - '14250:14250'

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - '9100:9100'
    networks:
      - app-network

volumes:
  prometheus_data:
  loki_data:

networks:
  app-network:
    driver: bridge
    # Verbesserte Netzwerk-Isolation
    internal: false # Auf true setzen, wenn kein direkter Internet-Zugriff benötigt wird
    driver_opts:
      com.docker.network.bridge.name: app-net
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
